<a href="https://colab.research.google.com/github/DISHMITHACHINTAGUNTA/aiml-learning-journey/blob/master/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
lst = np.array([1,3,4])
print(lst*2)

[2 6 8]


# Difference b/w List and Numpy_Array

In [ ]:
# SPEED DIFF B/W LIST AND NUMPY ARRAY

import numpy as np
import time
a1=np.array([12,13,14,15])
print(a1)
a1

a=[1,2,3,4]*10000
b=np.array(a)
start=time.time()
new_b=b*2
print("time taken for numpy array:",time.time()-start)

a=[1,2,3,4]*10000
strt=time.time()
for i in range(len(a)):
  a[i]=a[i]*2
print("time taken for lists:", time.time()-strt)




[12 13 14 15]
time taken for numpy array: 0.0003788471221923828
time taken for lists: 0.00535893440246582


In [ ]:
# MEMORY DIFFERENCE B/W LIST AND NUMPY ARRAY

import sys
a=[1,2,3,4,5]
arr=np.array(a)
print("list size:",sys.getsizeof(a))
print("array size:",arr.nbytes)

list size: 104
array size: 40


In [ ]:
# NUMPY ALLOWS SAME DATATYPE

a=[1,2.4,"for you"]
arr=np.array(a)
print(a,type(a))
print(arr,type(arr))


[1, 2.4, 'for you'] <class 'list'>
['1' '2.4' 'for you'] <class 'numpy.ndarray'>


# BUILT-IN FUNCTIONS

In [ ]:
# DIIMENSIONS AND SHAPE OF AN ARRAY

#shpae =(no.of_elemnes in row,)
# shape= (row, column)
# shape=(layer/boxes,rows,columns)

scl=np.array(17)
print("dimension od scalar:",scl.ndim)
print("shape of the scl:",scl.shape)
arr=np.array([12,70])#1D
print("dimension of arr:",arr.ndim)
print("shape of the array:",arr.shape)
arr2=np.array([[16,17,18],[19,20,21]])#2D
print("Dimension of the arr2:",arr2.ndim)
print("shape of the arr2:",arr2.shape)
arr3=np.array([[[13,12],[14,15]]])# 3D
print("Dimension of arr3:",arr3.ndim)
print("shape of the arr3:",arr3.shape)

dimension od scalar: 0
shape of the scl: ()
dimension of arr: 1
shape of the array: (2,)
Dimension of the arr2: 2
shape of the arr2: (2, 3)
Dimension of arr3: 3
shape of the arr3: (1, 2, 2)


In [ ]:
# ASSIGNING VALUES IN ARRAY

arr =np.arange(1,20) # (start,stop)
arr2=np.arange(1,20,2) #(start,stop,step)
print(arr)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# linspace()- it si used when assigning specific no.of values between two numbers in an array.

arr=np.linspace(0,1,5)
print(arr)

arr2= np.linspace(10,20,30) # (start,stop, no.of values between them)
print(arr2)

[0.   0.25 0.5  0.75 1.  ]
[10.         10.34482759 10.68965517 11.03448276 11.37931034 11.72413793
 12.06896552 12.4137931  12.75862069 13.10344828 13.44827586 13.79310345
 14.13793103 14.48275862 14.82758621 15.17241379 15.51724138 15.86206897
 16.20689655 16.55172414 16.89655172 17.24137931 17.5862069  17.93103448
 18.27586207 18.62068966 18.96551724 19.31034483 19.65517241 20.        ]


In [ ]:
# logspace()- it creates numbers that are evenly spaced on log scale.
# default base - 10

a=np.logspace(2,1,5)
print(a)

b=np.logspace(1,5,3) # (start_exponent, stop_exponent, no.of_values)
print(b)

c= np.logspace(1,5,num=4,base=5)
print(c)

[100.          56.23413252  31.6227766   17.7827941   10.        ]
[1.e+01 1.e+03 1.e+05]
[   5.           42.74939867  365.50221728 3125.        ]


In [18]:
#np.zeros -> creates an array full of zeroe values.
#import numpy as np
arr= np.zeros(10 ,dtype=int)
print(arr)

a=np.zeros([2,5])
print(a)

# np.ones-> does same as zeros , but fill the array with ones

one=np.ones(3)
print(one)

one_matrix=np.ones([3,2],dtype=int)
print(one_matrix)



# np.full() -> it is used to fill the array with same value

defa_val=np.full([2,3],'jk') #(no.of_values, value_filled_in_array)
print(defa_val)

ad=np.full(7,7)
print(ad)





[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1.]
[[1 1]
 [1 1]
 [1 1]]
[['jk' 'jk' 'jk']
 ['jk' 'jk' 'jk']]
[7 7 7 7 7 7 7]


In [32]:
#np.empty ->unintialized array i.e it creates an array without setting/assigning any values in it.

arr=np.empty([2,3])
print(arr)

[[2.2705355e-312 2.2705355e-312 2.2705355e-312]
 [2.2705355e-312 2.2705355e-312 2.2705355e-312]]


In [36]:
# np.random.rand()-> it produce random float values (0 to 1)
arr= np.random.rand(2,4)
print(arr)

# np.random.randn -> it generate float values which can be -ve , mostly near to zero , and it based on normal distribution

arr_n=np.random.randn(2,4)
print(arr_n)

#np.random.randint() -> produce random integer values

arr_int=np.random.randint(13,200) #(start,stop)-> they randomly choose a value b/w them
arr3=np.random.randint(2,24,[2,3])
print(arr_int)
print(arr3)

[[0.50399582 0.91392933 0.23780603 0.39420604]
 [0.06536639 0.93890454 0.52858343 0.1307848 ]]
[[-1.82239064 -1.6682668  -0.2434839  -1.3558706 ]
 [ 0.20710451  0.08089244  0.75189947 -0.54640914]]
63
[[12 16 23]
 [23 20 10]]


# DATA TYPE AND TYPE CASTING
